# Warning! This is auto-generated SQL & LookML, generated by csv-sql.web.app.
# Doublecheck the dimensions and their datatypes and adjust where necessary.

# explore: csv_to_sql_query {}

view: dt_timeline_test {
  derived_table: {
    sql:
      SELECT
        'train_id_0' AS id, CAST('2016-01-03' AS DATE) AS datop, 'TU 0712 ' AS fltid, 'CMN' AS depstn, 'TUN' AS arrstn, CAST('2016-01-03 10:30:00' AS DATETIME) AS std, CAST('2016-01-03 12.55.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 32AIMN' AS ac, 260.0 AS target
      UNION ALL
      SELECT
        'train_id_1' AS id, CAST('2016-01-13' AS DATE) AS datop, 'TU 0757 ' AS fltid, 'MXP' AS depstn, 'TUN' AS arrstn, CAST('2016-01-13 15:05:00' AS DATETIME) AS std, CAST('2016-01-13 16.55.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 31BIMO' AS ac, 20.0 AS target
      UNION ALL
      SELECT
        'train_id_2' AS id, CAST('2016-01-16' AS DATE) AS datop, 'TU 0214 ' AS fltid, 'TUN' AS depstn, 'IST' AS arrstn, CAST('2016-01-16 04:10:00' AS DATETIME) AS std, CAST('2016-01-16 06.45.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 32AIMN' AS ac, 0.0 AS target
      UNION ALL
      SELECT
        'train_id_3' AS id, CAST('2016-01-17' AS DATE) AS datop, 'TU 0480 ' AS fltid, 'DJE' AS depstn, 'NTE' AS arrstn, CAST('2016-01-17 14:10:00' AS DATETIME) AS std, CAST('2016-01-17 17.00.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 736IOK' AS ac, 0.0 AS target
      UNION ALL
      SELECT
        'train_id_4' AS id, CAST('2016-01-17' AS DATE) AS datop, 'TU 0338 ' AS fltid, 'TUN' AS depstn, 'ALG' AS arrstn, CAST('2016-01-17 14:30:00' AS DATETIME) AS std, CAST('2016-01-17 15.50.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 320IMU' AS ac, 22.0 AS target
      UNION ALL
      SELECT
        'train_id_5' AS id, CAST('2016-01-17' AS DATE) AS datop, 'TU 0283 ' AS fltid, 'TLS' AS depstn, 'TUN' AS arrstn, CAST('2016-01-17 16:20:00' AS DATETIME) AS std, CAST('2016-01-17 18.15.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 736IOP' AS ac, 53.0 AS target
      UNION ALL
      SELECT
        'train_id_6' AS id, CAST('2016-01-18' AS DATE) AS datop, 'TU 0514 ' AS fltid, 'TUN' AS depstn, 'BCN' AS arrstn, CAST('2016-01-18 07:15:00' AS DATETIME) AS std, CAST('2016-01-18 09.00.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 32AIMH' AS ac, 10.0 AS target
      UNION ALL
      SELECT
        'train_id_7' AS id, CAST('2016-01-18' AS DATE) AS datop, 'TU 0716 ' AS fltid, 'TUN' AS depstn, 'ORY' AS arrstn, CAST('2016-01-18 07:35:00' AS DATETIME) AS std, CAST('2016-01-18 09.55.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 32AIMI' AS ac, 15.0 AS target
      UNION ALL
      SELECT
        'train_id_8' AS id, CAST('2016-01-18' AS DATE) AS datop, 'TU 0752 ' AS fltid, 'TUN' AS depstn, 'FCO' AS arrstn, CAST('2016-01-18 07:40:00' AS DATETIME) AS std, CAST('2016-01-18 09.00.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 32AIMC' AS ac, 16.0 AS target
      UNION ALL
      SELECT
        'train_id_9' AS id, CAST('2016-01-18' AS DATE) AS datop, 'TU 0996 ' AS fltid, 'TUN' AS depstn, 'NCE' AS arrstn, CAST('2016-01-18 07:45:00' AS DATETIME) AS std, CAST('2016-01-18 09.15.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 31AIMK' AS ac, 21.0 AS target
      UNION ALL
      SELECT
        'train_id_10' AS id, CAST('2016-01-18' AS DATE) AS datop, 'TU 0930 ' AS fltid, 'TUN' AS depstn, 'MRS' AS arrstn, CAST('2016-01-18 07:55:00' AS DATETIME) AS std, CAST('2016-01-18 09.30.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 32AIMF' AS ac, 12.0 AS target
      UNION ALL
      SELECT
        'train_id_11' AS id, CAST('2016-01-20' AS DATE) AS datop, 'TU 0724 ' AS fltid, 'TUN' AS depstn, 'ORY' AS arrstn, CAST('2016-01-20 18:30:00' AS DATETIME) AS std, CAST('2016-01-20 20.50.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 32AIMP' AS ac, 18.0 AS target
      UNION ALL
      SELECT
        'train_id_12' AS id, CAST('2016-01-20' AS DATE) AS datop, 'TU 0913 ' AS fltid, 'TUN' AS depstn, 'MED' AS arrstn, CAST('2016-01-20 19:40:00' AS DATETIME) AS std, CAST('2016-01-21 00.00.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 320IMR' AS ac, 0.0 AS target
      UNION ALL
      SELECT
        'train_id_13' AS id, CAST('2016-01-21' AS DATE) AS datop, 'TU 0217 ' AS fltid, 'IST' AS depstn, 'TUN' AS arrstn, CAST('2016-01-21 20:10:00' AS DATETIME) AS std, CAST('2016-01-21 23.00.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 320IMU' AS ac, 0.0 AS target
      UNION ALL
      SELECT
        'train_id_14' AS id, CAST('2016-01-22' AS DATE) AS datop, 'TU 0744 ' AS fltid, 'TUN' AS depstn, 'FRA' AS arrstn, CAST('2016-01-22 07:05:00' AS DATETIME) AS std, CAST('2016-01-22 09.40.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 736IOP' AS ac, 18.0 AS target
      UNION ALL
      SELECT
        'train_id_15' AS id, CAST('2016-01-22' AS DATE) AS datop, 'TU 0706 ' AS fltid, 'CMN' AS depstn, 'TUN' AS arrstn, CAST('2016-01-22 17:45:00' AS DATETIME) AS std, CAST('2016-01-22 20.10.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 320IMR' AS ac, 0.0 AS target
      UNION ALL
      SELECT
        'train_id_16' AS id, CAST('2016-01-22' AS DATE) AS datop, 'TU 0723 ' AS fltid, 'ORY' AS depstn, 'TUN' AS arrstn, CAST('2016-01-22 18:30:00' AS DATETIME) AS std, CAST('2016-01-22 21.00.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 332IFN' AS ac, 37.0 AS target
      UNION ALL
      SELECT
        'train_id_17' AS id, CAST('2016-01-23' AS DATE) AS datop, 'TU 0726 ' AS fltid, 'MIR' AS depstn, 'BRU' AS arrstn, CAST('2016-01-23 05:30:00' AS DATETIME) AS std, CAST('2016-01-23 08.15.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 31AIMJ' AS ac, 149.0 AS target
      UNION ALL
      SELECT
        'train_id_18' AS id, CAST('2016-01-22' AS DATE) AS datop, 'TU 0913 ' AS fltid, 'TUN' AS depstn, 'MED' AS arrstn, CAST('2016-01-22 19:40:00' AS DATETIME) AS std, CAST('2016-01-23 00.00.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 320IMT' AS ac, 30.0 AS target
      UNION ALL
      SELECT
        'train_id_19' AS id, CAST('2016-01-23' AS DATE) AS datop, 'TU 9038 ' AS fltid, 'TUN' AS depstn, 'DJE' AS arrstn, CAST('2016-01-23 08:50:00' AS DATETIME) AS std, CAST('2016-01-23 09.45.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 736IOL' AS ac, 19.0 AS target
      UNION ALL
      SELECT
        'train_id_20' AS id, CAST('2016-01-23' AS DATE) AS datop, 'TU 0717 ' AS fltid, 'ORY' AS depstn, 'TUN' AS arrstn, CAST('2016-01-23 10:55:00' AS DATETIME) AS std, CAST('2016-01-23 13.20.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 32AIMI' AS ac, 27.0 AS target
      UNION ALL
      SELECT
        'train_id_21' AS id, CAST('2016-01-24' AS DATE) AS datop, 'TU 0430 ' AS fltid, 'DJE' AS depstn, 'LYS' AS arrstn, CAST('2016-01-24 14:05:00' AS DATETIME) AS std, CAST('2016-01-24 16.25.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 31AIMJ' AS ac, 0.0 AS target
      UNION ALL
      SELECT
        'train_id_22' AS id, CAST('2016-01-27' AS DATE) AS datop, 'TU 0789 ' AS fltid, 'BRU' AS depstn, 'TUN' AS arrstn, CAST('2016-01-27 11:35:00' AS DATETIME) AS std, CAST('2016-01-27 14.15.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 32AIMF' AS ac, 31.0 AS target
      UNION ALL
      SELECT
        'train_id_23' AS id, CAST('2016-02-01' AS DATE) AS datop, 'TU 0913 ' AS fltid, 'TUN' AS depstn, 'MED' AS arrstn, CAST('2016-02-01 19:40:00' AS DATETIME) AS std, CAST('2016-02-02 00.00.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 320IMT' AS ac, 10.0 AS target
      UNION ALL
      SELECT
        'train_id_24' AS id, CAST('2016-02-02' AS DATE) AS datop, 'TU 0711 ' AS fltid, 'TUN' AS depstn, 'CMN' AS arrstn, CAST('2016-02-02 06:55:00' AS DATETIME) AS std, CAST('2016-02-02 09.40.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 320IMU' AS ac, 24.0 AS target
      UNION ALL
      SELECT
        'train_id_25' AS id, CAST('2016-02-02' AS DATE) AS datop, 'TU 0226 ' AS fltid, 'TUN' AS depstn, 'BEG' AS arrstn, CAST('2016-02-02 08:00:00' AS DATETIME) AS std, CAST('2016-02-02 10.05.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 32AIMN' AS ac, 9.0 AS target
      UNION ALL
      SELECT
        'train_id_26' AS id, CAST('2016-02-02' AS DATE) AS datop, 'TU 0723 ' AS fltid, 'ORY' AS depstn, 'TUN' AS arrstn, CAST('2016-02-02 18:30:00' AS DATETIME) AS std, CAST('2016-02-02 20.55.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 320IMR' AS ac, 0.0 AS target
      UNION ALL
      SELECT
        'train_id_27' AS id, CAST('2016-02-02' AS DATE) AS datop, 'TU 0397 ' AS fltid, 'TUN' AS depstn, 'OUA' AS arrstn, CAST('2016-02-02 18:30:00' AS DATETIME) AS std, CAST('2016-02-02 22.50.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 31BIMQ' AS ac, 0.0 AS target
      UNION ALL
      SELECT
        'train_id_28' AS id, CAST('2016-02-02' AS DATE) AS datop, 'TU 0217 ' AS fltid, 'IST' AS depstn, 'TUN' AS arrstn, CAST('2016-02-02 20:10:00' AS DATETIME) AS std, CAST('2016-02-02 23.00.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 32AIMN' AS ac, 0.0 AS target
      UNION ALL
      SELECT
        'train_id_29' AS id, CAST('2016-02-03' AS DATE) AS datop, 'TU 0398 ' AS fltid, 'ABJ' AS depstn, 'TUN' AS arrstn, CAST('2016-02-03 01:55:00' AS DATETIME) AS std, CAST('2016-02-03 07.05.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 31BIMQ' AS ac, 0.0 AS target
      UNION ALL
      SELECT
        'train_id_30' AS id, CAST('2016-02-03' AS DATE) AS datop, 'TU 0473 ' AS fltid, 'VCE' AS depstn, 'TUN' AS arrstn, CAST('2016-02-03 10:00:00' AS DATETIME) AS std, CAST('2016-02-03 11.45.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 320IMU' AS ac, 9.0 AS target
      UNION ALL
      SELECT
        'train_id_31' AS id, CAST('2016-02-04' AS DATE) AS datop, 'TU 0680 ' AS fltid, 'TUN' AS depstn, 'MRS' AS arrstn, CAST('2016-02-04 08:25:00' AS DATETIME) AS std, CAST('2016-02-04 10.00.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 31AIMK' AS ac, 49.0 AS target
      UNION ALL
      SELECT
        'train_id_32' AS id, CAST('2016-02-04' AS DATE) AS datop, 'TU 0700 ' AS fltid, 'TUN' AS depstn, 'GVA' AS arrstn, CAST('2016-02-04 12:40:00' AS DATETIME) AS std, CAST('2016-02-04 14.35.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 31BIMO' AS ac, 0.0 AS target
      UNION ALL
      SELECT
        'train_id_33' AS id, CAST('2016-02-04' AS DATE) AS datop, 'TU 0850 ' AS fltid, 'TUN' AS depstn, 'LYS' AS arrstn, CAST('2016-02-04 12:15:00' AS DATETIME) AS std, CAST('2016-02-04 14.05.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 736IOK' AS ac, 24.0 AS target
      UNION ALL
      SELECT
        'train_id_34' AS id, CAST('2016-02-04' AS DATE) AS datop, 'TU 0756 ' AS fltid, 'TUN' AS depstn, 'MXP' AS arrstn, CAST('2016-02-04 12:30:00' AS DATETIME) AS std, CAST('2016-02-04 14.15.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 32AIMN' AS ac, 12.0 AS target
      UNION ALL
      SELECT
        'train_id_35' AS id, CAST('2016-02-04' AS DATE) AS datop, 'TU 0208 ' AS fltid, 'TUN' AS depstn, 'NTE' AS arrstn, CAST('2016-02-04 12:50:00' AS DATETIME) AS std, CAST('2016-02-04 15.15.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 736IOR' AS ac, 7.0 AS target
      UNION ALL
      SELECT
        'train_id_36' AS id, CAST('2016-02-04' AS DATE) AS datop, 'TU 0635 ' AS fltid, 'MIR' AS depstn, 'DJE' AS arrstn, CAST('2016-02-04 15:05:00' AS DATETIME) AS std, CAST('2016-02-04 15.45.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 31AIMJ' AS ac, 20.0 AS target
      UNION ALL
      SELECT
        'train_id_37' AS id, CAST('2016-02-04' AS DATE) AS datop, 'TU 0757 ' AS fltid, 'MXP' AS depstn, 'TUN' AS arrstn, CAST('2016-02-04 15:05:00' AS DATETIME) AS std, CAST('2016-02-04 17.00.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 32AIMN' AS ac, 20.0 AS target
      UNION ALL
      SELECT
        'train_id_38' AS id, CAST('2016-02-05' AS DATE) AS datop, 'TU 0711 ' AS fltid, 'TUN' AS depstn, 'CMN' AS arrstn, CAST('2016-02-05 06:55:00' AS DATETIME) AS std, CAST('2016-02-05 09.40.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 320IMV' AS ac, 125.0 AS target
      UNION ALL
      SELECT
        'train_id_39' AS id, CAST('2016-02-05' AS DATE) AS datop, 'TU 0847 ' AS fltid, 'TUN' AS depstn, 'BEY' AS arrstn, CAST('2016-02-05 09:30:00' AS DATETIME) AS std, CAST('2016-02-05 12.45.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 31BIMO' AS ac, 13.0 AS target
      UNION ALL
      SELECT
        'train_id_40' AS id, CAST('2016-02-05' AS DATE) AS datop, 'TU 0881 ' AS fltid, 'AMS' AS depstn, 'TUN' AS arrstn, CAST('2016-02-05 10:10:00' AS DATETIME) AS std, CAST('2016-02-05 13.00.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 736IOK' AS ac, 37.0 AS target
      UNION ALL
      SELECT
        'train_id_41' AS id, CAST('2016-02-05' AS DATE) AS datop, 'TU 0745 ' AS fltid, 'FRA' AS depstn, 'TUN' AS arrstn, CAST('2016-02-05 10:30:00' AS DATETIME) AS std, CAST('2016-02-05 12.55.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 32AIMC' AS ac, 25.0 AS target
      UNION ALL
      SELECT
        'train_id_42' AS id, CAST('2016-02-05' AS DATE) AS datop, 'TU 0902 ' AS fltid, 'TUN' AS depstn, 'MRS' AS arrstn, CAST('2016-02-05 14:05:00' AS DATETIME) AS std, CAST('2016-02-05 15.45.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 736IOK' AS ac, 50.0 AS target
      UNION ALL
      SELECT
        'train_id_43' AS id, CAST('2016-02-05' AS DATE) AS datop, 'TU 0717 ' AS fltid, 'ORY' AS depstn, 'TUN' AS arrstn, CAST('2016-02-05 10:55:00' AS DATETIME) AS std, CAST('2016-02-05 13.15.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 320IMS' AS ac, 12.0 AS target
      UNION ALL
      SELECT
        'train_id_44' AS id, CAST('2016-02-05' AS DATE) AS datop, 'TU 0515 ' AS fltid, 'BCN' AS depstn, 'TUN' AS arrstn, CAST('2016-02-05 16:40:00' AS DATETIME) AS std, CAST('2016-02-05 18.15.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 320IMS' AS ac, 93.0 AS target
      UNION ALL
      SELECT
        'train_id_45' AS id, CAST('2016-02-05' AS DATE) AS datop, 'TU 0724 ' AS fltid, 'TUN' AS depstn, 'ORY' AS arrstn, CAST('2016-02-05 18:30:00' AS DATETIME) AS std, CAST('2016-02-05 20.50.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 32AIMN' AS ac, 10.0 AS target
      UNION ALL
      SELECT
        'train_id_46' AS id, CAST('2016-02-06' AS DATE) AS datop, 'TU 0635 ' AS fltid, 'ORY' AS depstn, 'DJE' AS arrstn, CAST('2016-02-06 17:40:00' AS DATETIME) AS std, CAST('2016-02-06 20.25.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 320IMS' AS ac, 147.0 AS target
      UNION ALL
      SELECT
        'train_id_47' AS id, CAST('2016-02-07' AS DATE) AS datop, 'TU 0714 ' AS fltid, 'JED' AS depstn, 'TUN' AS arrstn, CAST('2016-02-07 00:55:00' AS DATETIME) AS std, CAST('2016-02-07 05.30.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 332IFM' AS ac, 15.0 AS target
      UNION ALL
      SELECT
        'train_id_48' AS id, CAST('2016-02-08' AS DATE) AS datop, 'TU 0339 ' AS fltid, 'ALG' AS depstn, 'TUN' AS arrstn, CAST('2016-02-08 17:00:00' AS DATETIME) AS std, CAST('2016-02-08 18.10.00' AS DATETIME) AS sta, 'ATA' AS status, 'TU 320IMU' AS ac, 0.0 AS target

      ;;
  }

  dimension: id {
    type: string
    sql: ${TABLE}.id ;;
  }

  dimension: datop {
    type: date
    datatype: date
    sql: ${TABLE}.datop ;;
  }

  dimension: fltid {
    type: string
    sql: ${TABLE}.fltid ;;
  }

  dimension: depstn {
    type: string
    sql: ${TABLE}.depstn ;;
  }

  dimension: arrstn {
    type: string
    sql: ${TABLE}.arrstn ;;
  }

  dimension: std {
    type: date_time
    datatype: date
    sql: ${TABLE}.std ;;
    #html: {{ rendered_value | date: "%Y-%m-%d %H:%M" }};;
  }

  dimension: sta {
    type: date_time
    datatype: date
    sql: ${TABLE}.sta ;;
  }

  dimension: status {
    type: string
    sql: ${TABLE}.status ;;
  }

  dimension: ac {
    type: string
    sql: ${TABLE}.ac ;;
  }

  dimension: target {
    type: number
    sql: ${TABLE}.target ;;
  }

  measure: count {
    type: count
  }

  dimension: total_visit_duration {
    type: number
    sql: ${TABLE}.target;;
    hidden:  yes
  }

  dimension: visit_start_time {
    type: date_time
    sql: ${TABLE}.std ;;
  }

  dimension: visit_end_time {
    type: date_time
    sql: TIMESTAMPADD(SECOND,${TABLE}.target,${TABLE}.std) ;;
  }

  measure: Total_duration {
    type: sum
    sql: ${TABLE}.target

          ;;
  }

}
